apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: danieloh30-poi-map-app-dev
  annotations:
    argocd/app-name: danieloh30-poi-map-app-dev
    backstage.io/kubernetes-id: danieloh30-poi-map-app-dev
    backstage.io/kubernetes-namespace: danieloh30
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=danieloh30-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rosa916-rvhvd/danieloh30-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/dev-pipelines/ns/danieloh30/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa916.9nln.p1.openshiftapps.com/k8s/ns/danieloh30/deployments/danieloh30-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa916.9nln.p1.openshiftapps.com/#https://github.com/rosa916-rvhvd/danieloh30-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://danieloh30-poi-map-app-danieloh30.apps.rosa916.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/danieloh30"
  system: workshop-system-danieloh30
  consumesApis:
    - gateway-api-danieloh30
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-danieloh30
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/danieloh30"
